### ISSUE TITLE
edmunds.com

### ISSUE THREAD

**Issue by ghajini** [gorhill/uBO-Extra#99]
@gorhill 
url affected=
`edmunds.com`

issue=
g00/instart logic on this site, loading infinitely ,high cpu usage

screenshot=
![screenshot 28](https://user-images.githubusercontent.com/20338483/44225734-de8c0d00-a1ab-11e8-84ab-26d32347e532.png)

reported here=
`https://github.com/uBlockOrigin/uAssets/issues/3164`
`https://github.com/jspenguin2017/uBlockProtector/issues/980`

**Comment by ghajini** [comment]
its timing issue(race condition)
sometimes i can reproduce/sometimes not
windows 10
page source code served:
`https://pastebin.com/729vALfp`
`https://pastebin.com/229BWzit`

**Comment by okiehsch** [comment]
I can reproduce this issue, sometimes I get redirected, sometimes uBO-extra works.
The same issue is present with uBO-extra 2.76 on my end.

**Comment by gorhill** [comment]
I am unable to reproduce. Looking at the pastebin'ed code above, it seems the IL code is loading from a file instead of from an inline script tag. If you use the following filter, is it still reproducible?

    ||g00.edmunds.com^*?i10c.$script,first-party

**Comment by okiehsch** [comment]
What does consistently fix the issue on my end, is to got to `edmunds.com` using uBO's medium mode.

**Comment by gorhill** [comment]
Doesn't this cause breakage?

On my side I only see `edmunds-media.com` being needed so far. So maybe we could use a `csp`-based filter.

**Comment by okiehsch** [comment]
Yes, it does break some functionality and it only woks on the homepage.
![image](https://user-images.githubusercontent.com/16838044/44494369-c4e73b80-a66b-11e8-9729-97d970c3db9b.png)

If I go to `edmunds.com/suv` with medium mode, I do get the redirection.
![unbenannt1](https://user-images.githubusercontent.com/16838044/44494496-476ffb00-a66c-11e8-82c1-6ab24556ce1c.PNG)

**Comment by okiehsch** [comment]
I can reproduce the issue on the homepage using Medium mode, if I load the site while I have opened the dev console and bypass the cache.
If I bypass the cache without opening the console I can't reproduce, this is really weird but I can reproduce the behaviour consistently.

**Comment by okiehsch** [comment]
`cnet.com` is another site I can reproduce redirections while nasdaq.com works fine which is strange considering both use the same Instart Logic code 
````
/Copyright Instart Logic Tue Jul 17 2018 - All rights reserved - version: 10.2.8
````

**Comment by gorhill** [comment]
I think they are wrapping their code with try-catch where it may throw from uBO-Extra hooks.

The only real solid solution for all that pain is to just use Firefox, maybe it's what we should advise first. Until Chromium supports HTML filtering (if ever), dealing with IL crap is a huge time sink.

**Comment by gorhill** [comment]
The filter I suggested above was for one file I saw at the top being declared and which contained the core IL code. But I see there are other such files declared later. So mainly they load multiple js files for their code (instead of or on top of the inline script tag), and uBO-Extra does not have an effect on these files except for the one I hard-coded a long time ago, which URL contains `instart.js`. The ones I see now have rather random names, I see no obvious patterns.

**Comment by okiehsch** [comment]
> they load multiple js files for their code (instead of or on top of the inline script tag)

Going to edmunds.com/suv with **everything** blocked except the `inline-script` I still get redirected.
![image](https://user-images.githubusercontent.com/16838044/44496583-6d4dcd80-a675-11e8-9f00-594c43d93933.png)

**Comment by okiehsch** [comment]
I can only reproduce the issue with a handful of the sites that are fixed by uBO-Extra and only if I am using Windows, I can't reproduce on any site with Linux, so I don't think this is a high priority issue atleast from my point of view.

**Comment by gorhill** [comment]
Can you give me that doc URL

**Comment by okiehsch** [comment]
?? you mean the URL's of the sites I get redirected?

**Comment by okiehsch** [comment]
````
view-source:https://www.edmunds.com/g00/?i10c.encReferrer=aHR0cHM6Ly93d3cuZWRtdW5kcy5jb20v&i10c.ua=1&i10c.dv=14
````

**Comment by gorhill** [comment]
I will have to give on just trying stuff, I would need to step into the code, but since I am never served IL code (even if using a US or India IP), there is nothing I can do for now.

**Comment by gorhill** [comment]
@okiehsch 

> I am never served IL code

Just to be clear, I see IL code with your `view-source` link above, but this expected given that this is an explicit `g00` link. I can't see IL code with `view-source:https://www.edmunds.com/` however, which is where things must always start.

**Comment by mapx-** [comment]
my edmunds page (italian ip)

https://pastebin.com/mXrg0y5X

**Comment by gorhill** [comment]
Ok, finally I found a way to reproduce: need a user agent string which tells the server my OS is Windows.

**Comment by gorhill** [comment]
Found an issue with uBO-Extra: turns out `edmunds.com` is also injected with another independant IL-defusing scriptlets, and in a silly mistake, the other scriptlet was being "defused" by the first one. Hopefully this is what was causing the issue.

**Comment by gorhill** [comment]
Although I fixed the self-inflicted defusing, I wonder the second scriptlet is still really needed: <https://github.com/gorhill/uBO-Extra/blob/master/contentscript.js#L455>.

I commented out `edmunds.com` and the site seems to still work just fine.

**Comment by gorhill** [comment]
I used this user agent switcher by the way: <https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg>. Open source, [developed in full view](https://github.com/ray-lothian/UserAgent-Switcher/), Mozilla Public License.

**Comment by gorhill** [comment]
Unable to reproduce so far. Tried with a US IP + Chrome/Windows user agent.

**Comment by okiehsch** [comment]
Like gwarser I can still repdroduce with 2.76. I don't get any IL-code at `boston.com` though.
Anyway, `edmunds.com` and `cnet.com` still have the same issue on my end, using Windows 10

> Just  to confirm, I can reproduce when I turn off uBO-Extra, thus confirming I am being served IL.

Does that mean that you do get redirections with 2.75 enabled at `edmunds.com` ?
I ask because even using the `User-Agent Switcher` with my Linux desktop I can't reproduce any actual redirection or g00-ads. The same is true with an old Windows 7 Laptop.
Maybe it is a browser bug as jspenguin2017 [suspects](https://github.com/jspenguin2017/uBlockProtector/issues/980#issuecomment-412297403)

**Comment by ghajini** [comment]
i can confirm findings of gwarser & okiehsch 
like 7/10 case i can produce........... refresh >clear data> refresh page ,IL IS back to foot
***my setup***
***ubo dev build 1.16.17b9***
***ubo extra 2.76***

`edmunds.com`
`nasdaq.com`
`boston.com`

**Comment by gorhill** [comment]
> Does that mean that you do get redirections with 2.75 enabled at edmunds.com ?

Yes, after I ...

- install uBO-Extra 2.75
- US IP
- Windows 10/Chrome 68 user agent string
- Clean all cache/cookies

I get IL redirections.

Then after I ...

- install uBO-Extra 2.75
- Clean all cache/cookies

No more redirections -- leaving both US IP and user agent unchanged.

**Comment by gorhill** [comment]
For `boston.com`, an new issue should be opened -- I can't reproduce IL redirections on my side -- i.e. works as expected with uBO-Extra.

**Comment by okiehsch** [comment]
I can reproduce redirectons only at
````
cnet.com
edmunds.com
gamespot.com
````
With all of these domains the redirections also occur if I use uBO-Extra 2.76 and a fresh profile.
